name: User Story
description: Create a User Story
title: "User Story: "
labels: ["user story"]
assignees:
  - stephenalandavis
body:
  - type: textarea
    id: story
    attributes:
      label: Story
      value: |
        **As the** ,
        **I want to** ,
        **so that** .
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ] **Given** , **when** , **then** .
    validations:
      required: true
  - type: textarea
    id: notes-and-details
    attributes:
      label: Notes and Details
      value: |
        - 
    validations:
      required: false
